
// Setting variables for html elements.

const computerResultElement = document.getElementById("computer_result");
const sumResultElement = document.getElementById("sum_result");
const winOrLoseResultElement = document.getElementById("win_or_lose_result");
const choiceOfUserElement = document.getElementById("choice_of_user");
const numberOfUserElement = document.getElementById("number_of_user");

/* Event listener to start program. WELL AWARE THAT I SHOULD 
HAVE USED A SUBMIT BUTTON, WANTED TO TEST THE "CHANGE" EVENT 
WITH SELECT ELEMENTS. */

numberOfUserElement.addEventListener("change", function() {

    // Get value of both select elements.

    const choiceOfUser = choiceOfUserElement.value;
    const numberOfUser = numberOfUserElement.value;
    
    // Calls function to generate randomly computer number.

    const numberOfComputer = computerNumberGenerator();

    // Calls function to sum user number and computer number.

    const numbersSum = sum(numberOfUser, numberOfComputer);

    /* "numberOfComputer" and "numbersSum" are passed as content of 
    "computerResultElement" and "sumResultElement" using "innerHtml" 
    proprety */

    computerResultElement.innerHTML = `Number for computer is ${numberOfComputer}`;

    sumResultElement.innerHTML = `Sum of user and computer number is ${numbersSum}`;

    /* Select structure compares "choiceOfUser" with return of "evenOrOdd()", 
    if it matches, user wins. Else, he loses */

    if (choiceOfUser === evenOrOdd(numbersSum)) {

        winOrLoseResultElement.innerHTML = `User WINS!!`

    } else {

        winOrLoseResultElement.innerHTML = `User LOSES!! Computer Wins`

    }

}

)

// Functions

/**
 * Returns a random number between 1 and 5
 * @returns {number}
 */

function computerNumberGenerator () {

    const randomNumber = ((Math.floor(Math.random() * 5) + 1));

    return randomNumber;

}

/**
 * Returns the sum of the number input by user and the 
 * random number generated by "computerNumberGenerator() 
 * after converting them to number type"
 * @param {string} userNumber
 * @param {string} computerNumber
 * @returns {number}
 */

function sum (userNumber, computerNumber) {

    const userNumberConverted = parseInt(userNumber);
    const computerNumberConverted = parseInt(computerNumber);

    sumOfNumbers = userNumberConverted + computerNumberConverted;

    return sumOfNumbers;

}

/**
 * Checks if the sum of he number input by user and the 
 * random number generated by "computerNumberGenerator() 
 * is even or odd
 * @param {number} numbersSumParameter
 * @returns {string}
 */

function evenOrOdd (numbersSumParameter) {

    if(numbersSumParameter % 2 === 0) {

        return "even";

    } else {

        return "odd";

    }

}


